"""Add password hash and email

Revision ID: 377b6c669825
Revises: 1dea7aac433b
Create Date: 2021-06-15 10:27:30.561815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '377b6c669825'
down_revision = '1dea7aac433b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
