"""Comments table

Revision ID: a9f9d0db79b8
Revises: 377b6c669825
Create Date: 2021-06-15 21:41:21.784701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9f9d0db79b8'
down_revision = '377b6c669825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pitch_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitch.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pitch', sa.Column('user_id', sa.String(), nullable=True))
    op.drop_column('pitch', 'likes')
    op.drop_column('pitch', 'dislikes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('dislikes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pitch', sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('pitch', 'user_id')
    op.drop_table('comments')
    # ### end Alembic commands ###
